const data = {
  product: [
    {
      _id: 1,
      name: "Product 1",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 120,
      countInStock: 0,
      brand: "Nike",
      rating: "4.5",
      numReviews: "2",
      description: "High quality product",
    },
    {
      _id: 2,
      name: "Product 2",
      category: "Shirts",
      image: "/images/p2.jpg",
      price: 220,
      countInStock: 10,
      brand: "Nike",
      rating: "4.0",
      numReviews: "9",
      description: "normal quality product",
    },
    {
      _id: 3,
      name: "Product 3",
      category: "Pants",
      image: "/images/p3.jpg",
      price: 130,
      countInStock: 5,
      brand: "Nike",
      rating: "3.5",
      numReviews: "11",
      description: "bad quality product",
    },
    {
      _id: 4,
      name: "Product 4",
      category: "Pants",
      image: "/images/p4.jpg",
      price: 1204,
      countInStock: 0,
      brand: "Nike",
      rating: "5.0",
      numReviews: "15",
      description: "High quality product",
    },
    {
      _id: 5,
      name: "Product 5",
      category: "Shirts",
      image: "/images/p5.jpg",
      price: 520,
      countInStock: 9,
      brand: "Nike",
      rating: "2.5",
      numReviews: "19",
      description: "waste quality product",
    },
    {
      _id: 6,
      name: "Product 6",
      category: "Pants",
      image: "/images/p6.jpg",
      price: 620,
      countInStock: 1,
      brand: "Nike",
      rating: "4.0",
      numReviews: "25",
      description: "High quality product",
    },
  ],
};
export default data;
